### PR TITLE
Use std.parallelism.totalCPUs to implement logicalProcessorCount.

### PR DESCRIPTION
**Pull request by s-ludwig**
See vibe-d/vibe.d#2008.

### CODE REVIEW

**Comment by wilzbach** [comment]
@s-ludwig AppVeyor supports Teams. You can go to the teams page, add a new role and add the permission to rebuild jobs to it. Afterwards you can add GitHub teams to this role.
@ZombinDev told me about it yesterday and we managed to get it to work for DMD.

**Comment by dkgroot** [comment]
@wilzbach can you push this one through ?

**Comment by wilzbach** [comment]
I tried to restart by using the `git commit --amend` trick.
@s-ludwig any chance you can go to https://ci.appveyor.com/team, create new role which allows restarting builds and add a team from the vibe-d organization to it? Thanks!

**Comment by dkgroot** [comment]
@wilzbach code.dlang.org is currently down 😥, which explains the cause.

**Comment by s-ludwig** [comment]
Restarted the CI checks.

**Comment by wilzbach** [comment]
(Restarted the CIs.)

**Pull request merged**
