### PR TITLE
Fix resolveHost returning addresses that do not match the expected address family

### PR DESCRIPTION
**Pull request by Yoplitein**

### CODE REVIEW

**Comment by Geod24** [comment]
Test case ? What's the issue ?

**Comment by Yoplitein** [comment]
The code as is never checks the requested address family when doing a DNS query.

Consider the following:
```
logInfo("%s", resolveHost("ip6.me", AddressFamily.INET));
logInfo("%s", resolveHost("ip6.me", AddressFamily.INET6));
logInfo("%s", resolveHost("ip6only.me", AddressFamily.INET));
logInfo("%s", resolveHost("ip4only.me", AddressFamily.INET6));
```
which prints out
```
216.115.184.69:0
216.115.184.69:0
[2604:90:1:1:0:0:0:69]:0
216.115.184.69:0
```

**Comment by Geod24** [comment]
Can you rebase on master ?

**Comment by Geod24** [comment]
Just did it for you

**Comment by Geod24** [comment]
This only works with `select`, not the `epoll` or `cfrunloop`

**Comment by Yoplitein** [comment]
Very strange. I've run the test suite without issues on a Linux host with the epoll configuration. Reading Travis' output, it looks like the build is failing in `tests/args.sh`?

**Comment by Geod24** [comment]
Yes, the first test. Since it triggers for *all* non-select configuration I take it's not spurious.

**Comment by Geod24** [comment]
Nevermind it looks like a `dub` regression.

**Comment by wilzbach** [comment]
( I modified `args.sh`, s.t. we can see the output.)

**Comment by Geod24** [comment]
I worked around the bug and rebased on master

**Pull request merged**
