### PR TITLE
Add optional timeout parameter to resolveHost

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
I'm not sure how to write a test-case for this though.

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
The appveryor failures seem unrelated. Is the test-suite known to be flakey?

**Comment by AndrejMitrovic** [comment]
Also Travis:

> Test failed: core.exception.AssertError@tests/dirwatcher.d(51): Change is not what was expected, got: [DirectoryChange(modified, /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/dirwatcher_test_2321/foo), DirectoryChange(removed, /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/dirwatcher_test_2321/foo), DirectoryChange(added, /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/dirwatcher_test_2321/subdir/bar), DirectoryChange(modified, /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/dirwatcher_test_2321/subdir/bar), DirectoryChange(removed, /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/dirwatcher_test_2321/subdir/bar)] but expected: [DirectoryChange(added, /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/dirwatcher_test_2321/foo), DirectoryChange(modified, /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/dirwatcher_test_2321/foo), DirectoryChange(removed, /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/dirwatcher_test_2321/foo), DirectoryChange(added, /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/dirwatcher_test_2321/subdir/bar), DirectoryChange(modified, /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/dirwatcher_test_2321/subdir/bar), DirectoryChange(removed, /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/dirwatcher_test_2321/subdir/bar)]

This seems unrelated to me..

**Comment by Geod24** [comment]
It is, the testsuite for this project is more flakey than Agora's...

**Comment by s-ludwig** [comment]
It's really annoying because those tests only fail on the CI infrastructure and remote debugging there is not exactly the most efficient thing in the world. I'll have to dedicate some time to fix this - sometime.

I'll merge manually.

**Comment by Geod24** [comment]
@s-ludwig : The solution is https://github.com/vibe-d/vibe-core/pull/221

**Pull request merged**
