### PR TITLE
Fix compilation of the directory iteration code on additional POSIX based platforms

### PR DESCRIPTION
**Pull request by s-ludwig**
See #242

### CODE REVIEW

**Comment by Geod24** [comment]
```
source/vibe/core/file.d(1065,46): Error: undefined identifier `AT_SYMLINK_NOFOLLOW`
source/vibe/core/file.d(1048,17): Error: undefined identifier `timespec`
source/vibe/core/file.d(1059,12): Error: static assert:  "Found no nanoseconds fields in struct stat"
source/vibe/core/file.d(1072,24):        instantiated from here: `getTimeField!"st_mtim"`
dmd failed with exit code 1.
```

https://github.com/vibe-d/vibe-core/pull/250

I fixed the `AT_SYMLINK_NOFOLLOW` upstream but you'll need a workaround for the time being.

**Comment by s-ludwig** [comment]
Cherry picked the workflow commit from #250 and fixed another error.

**Comment by s-ludwig** [comment]
Okay, not sure what was going on with `timespec`, but it's now down to this:
```
Linking...
cc: No such file or directory
Error: linker exited with status 255
```

**Comment by s-ludwig** [comment]
Okay, let me just drop the workflow commit, so that this can get merged and then #250 is the one that adds the workflow...

**Pull request merged**
