### PR TITLE
Fix InterfaceProxy to work with null values.

### PR DESCRIPTION
**Pull request by s-ludwig**
Previously caused crashes and opCast!bool to return true for null instances.

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]

**Comment by wilzbach** [comment]
We should probably replace those flaky AppVeyor tests with GitHub actions.

**Comment by s-ludwig** [comment]
> We should probably replace those flaky AppVeyor tests with GitHub actions.

Yeah, would be nice to unify the CI. I haven't looked into GitHub actions so far, though (maybe I should have done that instead of migrating to appveyor.com).

**Comment by wilzbach** [comment]
> > We should probably replace those flaky AppVeyor tests with GitHub actions.
> 
> Yeah, would be nice to unify the CI. I haven't looked into GitHub actions so far, though (maybe I should have done that instead of migrating to appveyor.com).

If you enable GitHub actions for this repo, I can play with it on https://github.com/vibe-d/vibe-core/pull/229.

**Comment by s-ludwig** [comment]
Actions are enabled, could it be that the workflows name "test.yml" requires additional configuration before it gets executed?

**Comment by wilzbach** [comment]
Hmm, they run here: https://github.com/wilzbach/vibe-core/actions/runs/260953798
I think I need to open the PR from a branch of this repo -> https://github.com/vibe-d/vibe-core/pull/230

**Pull request merged**
