### PR TITLE
Fix CI errors and unittest compile error on certain compiler versions

### PR DESCRIPTION
**Pull request by s-ludwig**
Affects the CI of the vibe.d repository

### CODE REVIEW

**Comment by Geod24** [comment]
What's the `in` compiler bug ?

**Comment by Geod24** [comment]
If you can provide me a command line example of compilation and the error message, I can advise.
The obvious reason why you would get a linker error with `in` is if you are compiling a library with a different set of flag than what uses it (with one of those compiling with `-preview=in` but not the other). In which case it would be a feature, not a bug, as the alternative is memory corruption ;)

**Comment by s-ludwig** [comment]
I think it was with dub-registry where I had consistent unresolved symbol errors for all methods that used simple `in` parameters (both, DMD 2.109.1 and LDC 1.39.0). All is compiled in a single `dub build` run, so there should be no compiler argument differences and `-preview=in` shouldn't be involved, unless someone else sneaked it in somewhere. I didn't look for, or write, a bug report so far, because I'm still in a kind of clean-up process after upgrading MongoDB, which caused a little cascade of issues.

**Comment by Geod24** [comment]
https://github.com/dlang/dub/blob/5e2a8de28aa29805dc7db1f6990171f1e1267dab/dub.sdl#L10-L11

**Comment by s-ludwig** [comment]
Okay, I see. I had a quick look, but missed the obvious possibility of `dub`. Would moving those into the "application" configuration do any harm?

**Review by l-kramer — APPROVED** [review]

**Pull request merged**
