### PR TITLE
Cleanup deprecations in test-suite and update release notes

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Review by AndrejMitrovic — APPROVED** [review]
LGTM!

**Review by wilzbach — APPROVED** [review]

**Comment by Geod24** [comment]
@wilzbach : See the failures. I'm seeing them in https://github.com/vibe-d/vibe-core/pull/218 too. Looks like an issue with dub.

**Comment by wilzbach** [comment]
> @wilzbach : See the failures. I'm seeing them in #218 too. Looks like an issue with dub.

Yeah, the `LATEST` version auto-update broke and it was stuck at 1.18, which I noticed yesterday and pushed a corrected LATEST.
I failed to replicate it locally FWIW and it's very strange that it only happens with the `epoll` configuration...

Anyhow, I modified `args.sh`, s.t. we can see the output.

**Comment by Geod24** [comment]
@wilzbach : I modified it here too:
https://travis-ci.com/github/vibe-d/vibe-core/jobs/375574482

```
+./args.sh
Fail (no argument): '[main(aNQ/) INF] Perform test receive
[main(aNQ/) INF] Perform test receiveExisting
[main(aNQ/) INF] Perform test timeout
[main(aNQ/) INF] Perform test noTimeout
[main(aNQ/) INF] Perform test close
[main(vQEk) INF] Perform test "disconnect with pending data"'
The command "./travis-ci.sh" exited with 1.
```

It seems to be running `0-tcp.d` which is the "first" file in the folder.

**Comment by AndrejMitrovic** [comment]
It seems like the `dirwatcher.d` failures are related to the polling-based directory watcher on the Mac. Past commit seem to show these tests to be unreliable: https://github.com/vibe-d/vibe-core/commit/71a2172edf06d75476a8878bce5a315ae462d558

**Comment by Geod24** [comment]
I'll rebase this on master soon, and add the missing release notes

**Comment by Geod24** [comment]
Rebased, now just need to wait 3 hours for the CI...

**Comment by s-ludwig** [comment]
Or event longer, because apparently the dlang.org TLS certificate has expired, causing the CI setup to fail ;-)

But all Linux and Windows tests have passed and some macOS ones, too, so I'll just force-merge this.

**Comment by Geod24** [comment]
Thanks! I'll do the release then, unless you want to do it yourself ?

**Pull request merged**
